apiVersion: v1
kind: Pod
metadata:
  name: beacon-test3
  namespace: default
spec:
  containers:
  - name: beacon-test3
    image: suburbandad/prysmatic-beacon:latest
    imagePullPolicy: IfNotPresent
    args: ["--datadir","/data"]
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "4"
        memory: 3Gi
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: data3
---
apiVersion: v1
kind: Pod
metadata:
  name: beacon-test2
  namespace: default
spec:
  containers:
  - name: beacon-test2
    image: suburbandad/prysmatic-beacon:latest
    imagePullPolicy: IfNotPresent
    args: ["--datadir","/data"]
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "4"
        memory: 3Gi
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: data2
---
apiVersion: v1
kind: Pod
metadata:
  name: beacon-test1
  namespace: default
spec:
  containers:
  - name: beacon-test1
    image: suburbandad/prysmatic-beacon:latest
    imagePullPolicy: IfNotPresent
    args: ["--datadir","/data"]
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "2"
        memory: "2500Mi"
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: data1
