kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "grafana"
spec:
  rules:
    - host: grafana.home
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 80
